name: ci
on: pull_request

env:
  BATON_LOG_LEVEL: debug
  BATON_TOKEN: "${{ secrets.BATON_TOKEN }}"
  BATON_PROCORE_CLIENT_ID: "${{ secrets.BATON_PROCORE_CLIENT_ID }}"
  BATON_PROCORE_CLIENT_SECRET: "${{ secrets.BATON_PROCORE_CLIENT_SECRET }}"

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m

  test-projects:
    runs-on: ubuntu-latest
    env:
      CONNECTOR_GRANT: 'project:598134326135521:member:user:13753064'
      CONNECTOR_ENTITLEMENT: 'project:598134326135521:member'
      CONNECTOR_PRINCIPAL: '13753064'
      CONNECTOR_PRINCIPAL_TYPE: 'user'
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build baton-procore
        run: go build ./cmd/baton-procore
      - name: Run baton-procore
        run: ./baton-procore
      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin

      - name: Check for grant before revoking
        run: |
          baton grants --entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --output-format=json | \
          jq --exit-status ".grants[].principal.id.resource == \"${{ env.CONNECTOR_PRINCIPAL }}\""

      - name: Revoke grants
        run: ./baton-procore --revoke-grant="${{ env.CONNECTOR_GRANT }}"

      - name: Check grant was revoked
        run: |
          ./baton-procore && \
          baton grants --entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --output-format=json | \
          jq --exit-status "if .grants then .grants[]?.principal.id.resource != \"${{ env.CONNECTOR_PRINCIPAL }}\" else . end"

      - name: Grant entitlement
        run: |
          ./baton-procore --grant-entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" \
                          --grant-principal="${{ env.CONNECTOR_PRINCIPAL }}" \
                          --grant-principal-type="${{ env.CONNECTOR_PRINCIPAL_TYPE }}"

      - name: Check grant was re-granted
        run: |
          ./baton-procore && \
          baton grants --entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --output-format=json | \
          jq --exit-status ".grants[].principal.id.resource == \"${{ env.CONNECTOR_PRINCIPAL }}\""

